name: onlysports_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0' # Adjusted for Flutter 3.22.0 compatibility

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1 # Check for latest version
  hive: ^2.2.3 # Check for latest version
  hive_flutter: ^1.1.0 # Check for latest version
  json_annotation: ^4.9.0 # Check for latest version
  dio: ^5.5.0+1 # Check for latest version
  intl: ^0.19.0 # Check for latest version - For date formatting
  path_provider: ^2.1.3 # Check for latest version
  # shared_preferences: ^2.2.3 # Removed - Migrated persistence to Hive
  skeletonizer: ^1.0.1 # Check for latest version - For skeleton loading
  cached_network_image: ^3.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Downgraded for Dart 3.4 compatibility
  riverpod_annotation: ^2.3.5 # Check for latest version
  hive_generator: ^2.0.1 # Check for latest version
  build_runner: ^2.4.11 # Check for latest version
  json_serializable: ^6.8.0 # Check for latest version

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    # - assets/fonts/ # Removed - Specific fonts are declared below
    # Add other asset paths here (e.g., images, rive)

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

