name: onlysports_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1 # Check for latest version
  json_annotation: ^4.9.0 # Check for latest version
  dio: ^5.5.0+1 # Check for latest version
  intl: ^0.19.0 # Check for latest version - For date formatting
  shared_preferences: ^2.2.3 # Check for latest version - For local storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_annotation: ^2.3.5 # Check for latest version
  build_runner: ^2.4.11 # Check for latest version
  json_serializable: ^6.8.0 # Check for latest version

flutter:
  uses-material-design: true
